name: Ghink
url: "http://ghink.arrifana.org/"
description: "Ghink is a github pages, plus InK, plus Jekyll boilerplate. An easy way to start a beautiful, responsive, self-hosted, blog or website"
disqus_shortname: "ghink"
use_leaflet: 1
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "blog/page/:num"
timezone: Europe/Lisbon
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
